version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci_parctice_test
    working_directory: ~/circleci_parctice
    steps:
      - checkout
      - run:
          name: "bundle install"
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}-1
          paths:
            - vendor/bundle
      - restore_cache:
          name: "restore yarn cache"
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}-1
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "yarn install"
          command: |
            yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          name: "save yarn cache"
          key: yarn-packages-{{ checksum "yarn.lock" }}-1
          paths:
            - ~/.cache/yarn
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec


workflows:
  version: 2
  workflows:
    jobs:
      - test
